site_name:           ModularForms.jl
repo_url:            https://gitlab.com/mraum/modularforms.jl
site_description:    ModularForms.jl
site_author:         Martin Raum

theme:               readthedocs

# pages:
# - Getting Started:      index.md
# - Modular Group:        modular_group.md
# - Cyclotomic Fields:    cyclotomic_fields.md

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math:
      enable_dollar_delimiter: True

docs_dir: 'build'

extra_javascript: ['mathjaxhelper.js', 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-AMS_HTML']
